// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAd7raeXxrkLf0s8uk8oeOX6FqEWBUmqnM',
    appId: '1:572556484221:web:bfccedac8832e9cfa59b14',
    messagingSenderId: '572556484221',
    projectId: 'pokedex-e85d3',
    authDomain: 'pokedex-e85d3.firebaseapp.com',
    storageBucket: 'pokedex-e85d3.firebasestorage.app',
    measurementId: 'G-S2HCLFVSC9',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBVtCPxpJLKZk63avRBb3ZfkfTlu9eN0Ic',
    appId: '1:572556484221:android:96ca228f3631782ca59b14',
    messagingSenderId: '572556484221',
    projectId: 'pokedex-e85d3',
    storageBucket: 'pokedex-e85d3.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBJppMlBed8lApVqk-btl8FUW4ICGH9yqk',
    appId: '1:572556484221:ios:3734e0c86af5a6d5a59b14',
    messagingSenderId: '572556484221',
    projectId: 'pokedex-e85d3',
    storageBucket: 'pokedex-e85d3.firebasestorage.app',
    iosBundleId: 'com.example.appTest',
  );
}
